### PR TITLE
update to 2.2

### PR DESCRIPTION
**Pull request by RoootTheFox**
Updates the mod to 2.2

still WIP, basic shaders work but all the audio/FMOD stuff is temporarily disabled until I figure out how to deal with the inlined? `FMODAudioEngine::enableMetering` on windows (bindings)

### CODE REVIEW

**Comment by RoootTheFox** [comment]
I also thought of splitting the source code up in multiple source files, since currently everything is in main.cpp and its a bit messy lol

**Comment by RoootTheFox** [comment]
the mod should be fully working now apart from macOS which i can't really test.
android does work too although i didn't get to testing audio/fft yet
windows fully works

**Comment by cgytrus** [comment]
would be nice if mac could be fixed and tested by someone (if anyone even cares about it anymore), also pulse is still off
i'll look over and fix some code style related stuff later, other than that, looks good so far

**Comment by RoootTheFox** [comment]
hi @cgytrus, do u still plan on working on this? if not, i might start refactoring the code base a little in a few days or weeks if i have the time and motivation.

**Comment by cgytrus** [comment]
(almost) everything seems to be working now, windows and android64 seem to be stable, the default shader breaks on mac, will test everything again including android32 after mac is fixed

**Pull request merged**
